        db      0FFh
        dw      10
        db      0FFh
        dw      1
        dw      1030h
        dd      5
        db      'HELLO'
        db      'MYTYPE', 0
        db      'DATA1', 0
        dw      1030h
        dd      4
        db      1, 2, 3, 4
        db      0FFh
        dw      10
        db      0FFh
        dw      2
        dw      1030h
        dd      3
        db      'ABC'
