DECLARE SUB Say (n AS INTEGER)
DECLARE SUB HELLO ()
Say 0
Say 1
Say 2
Say 3
Say 4
Say 5
Say 6
Say 7
Say 8
Say 9
Say 10
Say 11
Say 12
Say 13
Say 14
Say 15
Say 16
Say 17
Say 18
Say 19
Say 20
Say 21
Say 22
Say 23
Say 24
Say 25
Say 26
Say 27
Say 28
Say 29
Say 30
Say 31
Say 32
Say 33
Say 34
Say 35
Say 36
Say 37
Say 38
Say 39
HELLO
SYSTEM

SUB Say (n AS INTEGER)
  PRINT n;
END SUB
