bits 32
        dd      0, 32
        dw      0FFFFh, 0, 0FFFFh, 0
        dd      0
        dw      0, 0
        dd      0, 0
        dd      5, 32
        dw      0FFFFh, 10, 0FFFFh, 1
        dd      0
        dw      30h, 409h
        dd      0, 0
        db      'HELLO', 0, 0, 0
        dd      4, 52
        db      'M',0,'Y',0,'T',0,'Y',0,'P',0,'E',0,0,0
        db      'D',0,'A',0,'T',0,'A',0,'1',0,0,0
        dw      0
        dd      0
        dw      30h, 409h
        dd      0, 0
        db      1, 2, 3, 4
