all : T01.COM

T01.COM: T01.RDF T02.RDF ..\..\BIN\RLINK.EXE
	..\..\BIN\RLINK com /o=T01.COM T01.RDF T02.RDF
T01.RDF: T01.ASM
	nasm -f rdf T01.ASM
T02.RDF: T02.ASM
	nasm -f rdf T02.ASM
clean:
	DEL *.RDF
	DEL T01.COM
